name: dice-wire unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Install dependencies
        run: go get -v .
      - name: Run Unit tests
        run: make unittest
